FROM amazoncorretto:21.0.4-alpine3.18

WORKDIR /app

ENV ORDER_SERVICE_URL=${ORDER_SERVICE_URL}
ENV SPRING_KAFKA_BOOTSTRAP_SERVERS=${SPRING_KAFKA_BOOTSTRAP_SERVERS}

COPY target/order-receiver-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]