version: '3.8'
services:
  receiver:
    image: julioborges05/ordermanagement-receiver
    container_name: ordermanagement-receiver
    environment:
      - ORDER_SERVICE_URL=http://order:8089/order
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=broker:29092
    depends_on:
      - broker
    ports:
      - "8080:8080"