version: '3.8'
services:
  inventory-db:
    image: postgres:latest
    container_name: inventory-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=inventory-db
    ports:
      - "5437:5432"

  inventory:
    image:  rodrigodiasflamia/inventory
    container_name: ordermanagement-inventory
    environment:
      - DB_URL=jdbc:postgresql://inventory-db:5432/inventory-db
      - DB_USER=user
      - DB_PASSWORD=password
    depends_on:
      - inventory-db
    ports:
      - "8085:8080"

  order-db:
    image: postgres:latest
    container_name: order-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=order-db
    ports:
      - "5436:5432"

  order:
    image: dnrmth/ordermanagement-order:latest
    container_name: ordermanagement-order
    environment:
      - DB_URL=jdbc:postgresql://order-db:5432/order-db
      - DB_USER=user
      - DB_PASSWORD=password
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=broker:29092
      - PAYMENT_SERVICE_URL=http://payment:8080/payment
      - CLIENT_SERVICE_URL=http://client:8082/client/api
      - PRODUCT_SERVICE_URL=http://product:8080/product
      - STOCK_SERVICE_URL=http://inventory:8080/inventory
    depends_on:
      - order-db
      - broker
    ports:
      - "8084:8080"

  payment-db:
    image: postgres:latest
    container_name: payment-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=payment-db
    ports:
      - "5435:5432"

  payment:
    image: marques67/payment:1.0
    container_name: ordermanagement-payment
    environment:
      - DB_URL=jdbc:postgresql://payment-db:5432/payment-db
      - DB_USER=user
      - DB_PASSWORD=password
    depends_on:
      - payment-db
    ports:
      - "8083:8080"

  receiver:
    image: julioborges05/ordermanagement-receiver
    container_name: ordermanagement-receiver
    environment:
      - ORDER_SERVICE_URL=http://receiver:8080
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=broker:29092
    depends_on:
      - broker
    ports:
      - "8080:8080"

  product-db:
    image: postgres:latest
    container_name: product-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=product-db
    ports:
      - "5433:5432"

  product:
    image: anagenova/ordermanagement-product
    container_name: ordermanagement-product
    environment:
      - DB_URL=jdbc:postgresql://product-db:5432/product-db
      - DB_USER=user
      - DB_PASSWORD=password
    depends_on:
      - product-db
      - receiver
    ports:
      - "8081:8080"

  client-db:
    image: postgres:latest
    container_name: client-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=client-db
    ports:
      - "5434:5432"

  client:
    image: julioborges05/ordermanagement-client
    container_name: ordermanagement-client
    environment:
      - DB_URL=jdbc:postgresql://client-db:5432/client-db
      - DB_USER=user
      - DB_PASSWORD=password
    depends_on:
      - client-db
      - receiver
    ports:
      - "8082:8082"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-server:7.2.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'